### ISSUE TITLE
BetterDiscord plugins broke due to new discord update

### ISSUE THREAD

**Issue by VirginitySnatcher** [BrandonXLF/BetterDiscordPlugins#2]
All plugins don't work because of the new discord update, is it possible to update this plugin?

**Comment by BrandonXLF** [comment]
KeepCurrentChannel and RelativeTimestamps have been fixed, I'll continue to work on fixing NotificationHistory

**Comment by aaronliu0130** [comment]
Ever since I installed the updated version of KeepCurrentChannel I've been experiencing crashes(the kind that gives you a reload button but don't have betterdiscord deactivate). They usually happen after I click a desktop notification from discord. 
<details>
  <summary>Other Plugins I have</summary>
  <p>BDFDB, BetterAudioPlayer, BetterFormattingRedux, BetterRoleColors, BugReportHelper, ChatAliases(which doesn't really work), ClickableMentions, CopyRawMessage, DiscordFreeEmojis, Double Click To Edit, FactOfTheDay, ImageUtilities, NoReplyMention, PluginRepo, Translator, TypingIndicator, ZeresPluginLibrary</p>
</details>

**Comment by BrandonXLF** [comment]
NotificationHistory has now also been fixed.
